- hosts: servers
  vars:
    packages:
      - git
      - make
    users:
      - { name: jaime, groups: wheel }
      - { name: sansa, groups: wheel }
      - { name: robert, groups: root }
  tasks:
    - name: Create users
      tags: [create_users]
      loop: "{{ users | list }}"
      # when: item.name > 5
      loop_control:
        label: "{{ item.name }}"
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        shell: /bin/bash
        create_home: yes

    - name: Create gitconfig
      tags: [configuration]
      loop: "{{ users | list }}"
      loop_control:
        label: "{{ item.name }}"
      copy:
        dest: "/home/{{item.name}}/.gitconfig"
        owner: "{{ item.name }}"
        mode: '0644'
        content: |
          [alias]
            co = checkout
            ci = commit
            st = status
            br = branch
            hist = log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short
            type = cat-file -t
            dump = cat-file -p
            commend = commit --amend
          [core]
            excludesFile = ~/.gitignore_global
            editor = vim
          [user]
            email = {{item.name}}@test.com
            name = {{item.name}}
          [credential]
            helper = store

    - name: Install Packages CentOS
      become: yes
      tags: [install]
      when: ansible_distribution == "CentOS"
      dnf:
        update_cache: yes
        state: latest
        name: "{{ packages | list }}"

    - name: Install Packages Ubuntu
      become: yes
      tags: [install]
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes
        state: latest
        name: "{{ packages | list }}"

    - name: Add SSH public key for users
      tags: [configuration]
      loop: "{{ users | list }}"
      loop_control:
        label: "{{ item.name }}"
      authorized_key:
        user: "{{ item.name }}"
        manage_dir: yes
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"
        path: "/home/{{ item.name }}/.ssh/authorized_keys"