- hosts: servers_1
  vars:
    nginx_port: 80
    root_dir: /var/tmp/www
    nginx_config_path: /etc/nginx/nginx.conf

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: "Ensure {{root_dir}} exists"
      ansible.builtin.file:
        path: "{{root_dir}}"
        state: directory
        mode: '0755'
      become: yes
   
    - name: add static
      ansible.builtin.template:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
      become: yes

    - name: add nginx config
      ansible.builtin.template:
        src: files/nginx.conf
        dest: "{{nginx_config_path}}"
      become: yes
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
